import { Agent, AgentCategory, AgentRole } from './types';

export const predefinedAgents: Agent[] = [
  {
    id: "gpt-4",
    name: "GPT-4",
    category: AgentCategory.ASSISTANT,
    role: AgentRole.ASSISTANT,
    description: "GPT-4 is a large multimodal model that can solve difficult problems with accuracy.",
    model: "gpt-4",
    temperature: 0.7,
  },
  {
    id: "gpt-4-turbo",
    name: "GPT-4 Turbo",
    category: AgentCategory.ASSISTANT,
    role: AgentRole.ASSISTANT,
    description: "GPT-4 Turbo is the latest GPT-4 model with improved performance.",
    model: "gpt-4-turbo-preview",
    temperature: 0.7,
  },
  {
    id: "gpt-3.5-turbo",
    name: "GPT-3.5 Turbo",
    category: AgentCategory.ASSISTANT,
    role: AgentRole.ASSISTANT,
    description: "GPT-3.5 Turbo is a fast and efficient model for most tasks.",
    model: "gpt-3.5-turbo",
    temperature: 0.7,
  },
  {
    id: "claude-3-opus",
    name: "Claude 3 Opus",
    category: AgentCategory.ASSISTANT,
    role: AgentRole.ASSISTANT,
    description: "Claude 3 Opus is Anthropic's most powerful model for highly complex tasks.",
    model: "claude-3-opus-20240229",
    temperature: 0.7,
  },
  {
    id: "claude-3-sonnet",
    name: "Claude 3 Sonnet",
    category: AgentCategory.ASSISTANT,
    role: AgentRole.ASSISTANT,
    description: "Claude 3 Sonnet balances intelligence and speed for a wide range of tasks.",
    model: "claude-3-sonnet-20240229",
    temperature: 0.7,
  },
  {
    id: "claude-3-haiku",
    name: "Claude 3 Haiku",
    category: AgentCategory.ASSISTANT,
    role: AgentRole.ASSISTANT,
    description: "Claude 3 Haiku is Anthropic's fastest and most compact model.",
    model: "claude-3-haiku-20240307",
    temperature: 0.7,
  },
  {
    id: "claude-2",
    name: "Claude 2",
    category: AgentCategory.ASSISTANT,
    role: AgentRole.ASSISTANT,
    description: "Claude 2 is Anthropic's previous generation assistant.",
    model: "claude-2",
    temperature: 0.7,
  },
  {
    id: "gemini-pro",
    name: "Gemini Pro",
    category: AgentCategory.ASSISTANT,
    role: AgentRole.ASSISTANT,
    description: "Gemini Pro is Google's largest and most capable AI model.",
    model: "gemini-pro",
    temperature: 0.7,
  },
  {
    id: "mistral-large",
    name: "Mistral Large",
    category: AgentCategory.ASSISTANT,
    role: AgentRole.ASSISTANT,
    description: "Mistral Large is Mistral AI's most powerful model.",
    model: "mistral-large-latest",
    temperature: 0.7,
  },
  {
    id: "mistral-medium",
    name: "Mistral Medium",
    category: AgentCategory.ASSISTANT,
    role: AgentRole.ASSISTANT,
    description: "Mistral Medium balances performance and efficiency.",
    model: "mistral-medium-latest",
    temperature: 0.7,
  },
  {
    id: "mistral-small",
    name: "Mistral Small",
    category: AgentCategory.ASSISTANT,
    role: AgentRole.ASSISTANT,
    description: "Mistral Small is a fast and efficient model for most tasks.",
    model: "mistral-small-latest",
    temperature: 0.7,
  },
  {
    id: "llama3-70b",
    name: "Llama 3 70B",
    category: AgentCategory.ASSISTANT,
    role: AgentRole.ASSISTANT,
    description: "Llama 3 70B is Meta's largest and most capable open model.",
    model: "meta-llama/Llama-3-70b-chat-hf",
    temperature: 0.7,
  },
  {
    id: "llama3-8b",
    name: "Llama 3 8B",
    category: AgentCategory.ASSISTANT,
    role: AgentRole.ASSISTANT,
    description: "Llama 3 8B is Meta's smaller but efficient open model.",
    model: "meta-llama/Llama-3-8b-chat-hf",
    temperature: 0.7,
  },
];